# Generated by Django 5.0.1 on 2024-01-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bynary_tree',
            name='parent',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bynary_tree',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
